SELECT   
  E1_FILIAL, E1_PREFIXO, SE1.E1_TIPO, E1_NUM, E1_CODORCA, 
  E1_EMISSAO, MIN(SE1.E1_DTACRED) AS DATACRED,
  MIN(SE1.E1_PARCELA) AS PARCELA,
  COUNT(1) NUMPARCELAS,
  E1_CLIENTE, E1_LOJA, E1_NUMRA, E1_NOMCLI,
  E1_NRDOC,  E1_SALDO
FROM 
  DB2.SE1050 SE1 



WHERE 1=1
  AND SE1.E1_TIPO = 'CC' 
  -- AND SE1.E1_DTACRED <> ''
  AND SE1.E1_SALDO > 0 
  -- AND SE1.E1_NRDOC = '000001008'
  -- AND SE1.E1_DTACRED BETWEEN '".$DataInicio."' AND '".$DataFinal."'   
  AND SE1.E1_NRDOC <> ''  
  -- AND SE1.E1_CLIENTE = '078605'
  AND SE1.E1_LOJA = '01'  
  AND SE1.D_E_L_E_T_ = ' ' 
GROUP BY   
  E1_FILIAL, E1_PREFIXO, SE1.E1_TIPO, E1_NUM, E1_CODORCA, E1_EMISSAO,
  E1_CLIENTE, E1_LOJA, E1_NUMRA, E1_NOMCLI,
  E1_NRDOC,  E1_SALDO
  ORDER BY E1_NUM, E1_FILIAL , MIN(E1_PARCELA)